services:

 postgres :
   image: postgres :16
   port:
    - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aritraberea007
    volumes:
      - postgres_data:/var/lib/postgresql/data

volume:
  postgres_data
